name: Docker Image CI ${GITHUB_REF#refs/heads/}

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: script
      shell: bash
      run: |
        echo ${GITHUB_REF#refs/heads/}
