# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  WORKDIR: /home/ubuntu/simple-server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Terraform install
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install terraform
          
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        
      - name: Run terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        
      - name: Set Instance IP as Environment Variable
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          instance_ip=$(terraform output PUBLIC_IPV4)
          echo "INSTANCE_IP=$instance_ip" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    needs: [platform]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o ${{ github.event.repository.name }}

    - name: Test
      run: go test -v ./...
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: $instance_ip
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "./public,./templates,./${{ github.event.repository.name }}"
        target: ${{ env.WORKDIR }}
        
        
  run:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Use IP Address from Environment Variable
        run: |
          instance_ip=$INSTANCE_IP
          
      - name: Set and Run
        uses: appleboy/ssh-action@master
        with:
          host: $instance_ip
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ env.WORKDIR }}
            sudo systemctl restart ${{ github.event.repository.name }}
