# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  WORKDIR: /home/ubuntu/simple-server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Terraform install
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install terraform
          
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        
      - name: Run terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve
          echo "INSTANCE_IP=$(terraform output -raw PUBLIC_IPV4)" >> $GITHUB_ENV

      - name: Write IP to a file
        run: echo $INSTANCE_IP > instance-ip.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: instance-ip
          path: instance-ip.txt

  build:
    runs-on: ubuntu-latest
    needs: [platform]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: instance-ip
        path: ./ 
        
    - name: Set IP as env variable
      run: echo "INSTANCE_IP=$(cat instance-ip.txt)" >> $GITHUB_ENV
          
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o ${{ github.event.repository.name }}

    - name: Test
      run: go test -v ./...
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.INSTANCE_IP }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "./public,./templates,./${{ github.event.repository.name }}, ./${{ github.event.repository.name }}.service"
        target: ${{ env.WORKDIR }}
        
        
  run:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: instance-ip
          path: ./ 
        
      - name: Set IP as env variable
        run: echo "INSTANCE_IP=$(cat instance-ip.txt)" >> $GITHUB_ENV
          
      - name: Set service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sed -i 's|HOME|${{ env.WORKDIR }}|g' ${{ env.WORKDIR }}/${{ github.event.repository.name }}.service
            cat ${{ env.WORKDIR }}/${{ github.event.repository.name }}.service
            sudo mv ${{ env.WORKDIR }}/${{ github.event.repository.name }}.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl enable ${{ github.event.repository.name }}
          
      - name: Set and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ env.WORKDIR }}
            sudo systemctl restart ${{ github.event.repository.name }}
